### ISSUE TITLE
Stuck on Login Page

### ISSUE THREAD

**Issue by shineholiday** [sveltia/sveltia-cms#43] opened 2023-08-11 09:12 UTC
When I login with github, I get stuck on login page and it just leaves the message "Loading Site Data".

![image](https://github.com/sveltia/sveltia-cms/assets/138548614/0cb9e47a-2c89-4fe8-b39e-feaede70a34e)

**Comment by kyoshino** [comment] 2023-08-11 23:07
Now https://github.com/sveltia/sveltia-cms-auth/pull/2 is merged. Can you redeploy the auth script and try again? Thanks!

**Comment by kyoshino** [comment] 2023-08-15 00:14
Please feel free to reopen (possibly with a browser console log) if the problem persists!

**Closed by kyoshino** 2023-08-15 00:14 UTC
Labels: bug

**Comment by 0x0m0t0** [comment] 2023-10-03 16:52
Hello, I have this exact same issue. I'm also using the https://github.com/sveltia/sveltia-cms-auth sveltia auth system.

My localstorage shows content but it's stuck on the loading screen.

**Comment by kyoshino** [comment] 2023-10-03 17:06
The reported issue has been fixed so the cause might be different. Do you see any errors in the console? Is this your repository in question? https://github.com/0x0m0t0/astro-sveltia

**Comment by 0x0m0t0** [comment] 2023-10-03 17:20
Thanks for getting back to me, should I open a new issue?

There are no errors at all in the console. Although after I login with auth, the popup git window just dissapears and then I get stuck on the loading screen. 

This is indeed my repo, although my working branch is more up to date
https://github.com/0x0m0t0/astro-sveltia/tree/sveltia-vercel

**Comment by kyoshino** [comment] 2023-10-03 17:26
When I open your repository locally or just visit https://astro-sveltia.vercel.app/admin/ I see this error on the CMS UI:

> The configuration file could not be retrieved. Please solve the issue and try again.

The config path seems wrong. This line can be removed:

```html
<link href="admin/config.yml" type="text/yaml" rel="cms-config-url" />
```

**Comment by kyoshino** [comment] 2023-10-03 17:58
Okay, I could reproduce the issue after solving the config path issue, probably because there is no content yet. Since it’s a different problem from the original one, I’ll create a new issue.
