### ISSUE TITLE
Can't work with local repository from WSL2

### ISSUE THREAD

**Issue by razonyang** [sveltia/sveltia-cms#93] opened 2024-01-14 17:00 UTC
Hi, I encountered the following issue when trying to choose a folder from WSL2.

![image](https://github.com/sveltia/sveltia-cms/assets/17720932/c7aa30c4-9684-4e6d-a907-2321ecf5ec45)

**Comment by kyoshino** [comment] 2024-01-14 17:09
Duplicate of #92. Unfortunately, this issue cannot be solved on the CMS side.

**Closed by kyoshino** 2024-01-14 17:09 UTC
