### ISSUE TITLE
Rich Text Editor Thoughts XD

### ISSUE THREAD

**Issue by rchrdnsh** [sveltia/sveltia-cms#32] opened 2023-06-23 19:08 UTC
Hi!

So, the rich text editor is something that the teams I am working with will need before we can use Sveltia, and I have some thoughts...

What I ultimately want is a rich text editor where I can create custom svelte components that can be used as "blocks" that the content authors and editors are able to use in the composition of their writing. I want to be able to make custom components for them at their request, and/or offer a library for them to pick and choose from to add to their individual editing experience...

I believe Decep CMS uses Slate under the hood, but there are other more modern solutions like Prose Mirror that you might want to (or already are) considering...

I also recently found some interesting svelte based projects as well that might be useful:

tiptap, of course - https://github.com/ueberdosis/tiptap
svelte wrapper for tiptap - https://github.com/andheller/svelte-tiptap
Editable Website - https://github.com/michael/editable-website
Website for Editable Website to check it out - https://editable.website/
Svelte Prosemirror - https://github.com/TeemuKoivisto/svelte-prosemirror

all cool and interesting projects that I am learning more about to help my own understanding of these things.

Anyway, just wanted to share these resources as you work on rich text editing for Sveltia XD

**Comment by kyoshino** [comment] 2023-06-23 19:37
Yeah, for sure, a rich text editor is what I also need for my clients. The problem is some editor libraries have issues with editing multibyte characters like Chinese, Japanese, Korean and emojis. Anyway, I’ll implement one soonish.

**Comment by rchrdnsh** [comment] 2023-06-24 05:54
oooh, just found about about Lexical from Facebook:

https://github.com/facebook/lexical

...and there is a svelte wrapper, it would seem

https://github.com/umaranis/svelte-lexical

...dunno anything about it yet, tho

starting to learn how Prose Mirror works ATM :-)

**Comment by ngdangtu-vn** [comment] 2023-07-07 18:31
It would be great if you guys can add basic markdown editor.

**Comment by gryzzly** [comment] 2023-07-21 13:43
hey, a thought on editors and varying needs – what would be really cool is some guidance/tutorial for how to add custom editing fields widgets – that way we could try with any of the solutions above, and it’d not interfere with an "official" support eventually. 

thanks for this project!

**Comment by kyoshino** [comment] 2023-07-22 18:16
Hi, thanks for your comments! I’ll try to get this done before other projects start next month.

**Comment by kyoshino** [comment] 2023-09-04 20:46
Sorry for the delay folks! 🙇🏻  I quickly played around with Lexical and it looked good. No problem with editing Japanese, which is a must for my own clients. I’ll try to include it in the next minor release.

**Comment by kyoshino** [comment] 2023-09-08 09:20
As per https://github.com/decaporg/decap-cms/discussions/6905 Decap is switching to [Plate](https://platejs.org/). We should probably follow suit for plugin compatibility. Japanese (and probably Chinese and Korean) input works well on the Plate demo.

**Comment by kyoshino** [comment] 2023-09-08 09:41
Well, but Plate is basically a React library so I have to build the Svelte port from scratch. Lexical is framework agnostic. 🤔

**Comment by ngdangtu-vn** [comment] 2023-09-08 10:22
What about https://quilljs.com ?

**Comment by kyoshino** [comment] 2023-09-08 11:10
> What about https://quilljs.com ?

It looks pretty simple and framework agnostic, but not sure about the Markdown support. I’ll compare some options mentioned in this thread and make a final decision soon.

**Comment by rchrdnsh** [comment] 2023-09-14 19:38
IIRC Quill is kind of previous generation for rich text editors, and it looks like Plate is react based or only react? In any case I'm thinking Lexical or Prose Mirror / TipTap are maybe good choices...haven't look too deeply into the others however, just a quick glance at their sites...

**Comment by rchrdnsh** [comment] 2023-09-28 19:17
Any updates on the Rich Text Editor progress?

**Comment by Natetronn** [comment] 2023-12-12 05:50
A couple other options I've seen in my adventures, just in case it's of any use:

[Editor.js](https://editorjs.io/ ) - [Svelte Editor.js](https://github.com/pablo-abc/svelte-editorjs)

[Slate](https://github.com/ianstormtaylor/slate) - [Svelte Slate]( https://github.com/nathanfaucett/svelte-slate)

**Comment by kyoshino** [comment] 2023-12-19 00:49
Sorry folks for making you wait so long! 🙇🏼  I’m working on this now.

- Lexical isn’t well documented, but it seems to offer great flexibility. I’m playing around with this.
- Looks like [Quill](https://github.com/quilljs/quill/releases) has been updated very recently for the long-awaited v2 release. I’ll take a look at this as well.
- Slate is not an option because it has many issues related to [IMEs](https://en.wikipedia.org/wiki/Input_method) (Chinese, Japanese, Korean and Taiwanese), which is actually one of the reasons my clients wanted to move away from Netlify CMS.

**Comment by zanhk** [comment] 2023-12-23 17:04
[Lexical](https://github.com/facebook/lexical) looks promising

**Comment by kyoshino** [comment] 2023-12-24 02:25
Yeah, I’ll stick with Lexical. Quill 2.0 is still in early beta and having 1.3k+ open issues is concerning.

**Comment by rchrdnsh** [comment] 2023-12-24 03:38
I think lexical has svelte bindings as well, or there is a lib or something, so one could made nodes out of svelte components potentially...

**Comment by kyoshino** [comment] 2023-12-24 04:32
You’ve already pointed out [svelte-lexical](https://github.com/umaranis/svelte-lexical) 🙂 but I’m creating my own to keep using Sveltia UI, integrate the raw Markdown editor, and mimic the toolbar button layout of Netlify/Decap CMS.

<img width="653" alt="image" src="https://github.com/sveltia/sveltia-cms/assets/2929505/4ab76604-6def-4a1b-b718-50d6e05c801a">

**Comment by rchrdnsh** [comment] 2023-12-24 04:46
whoops, forgot about that 😁

In any case, thank you for all your hard work on this :-)

**Comment by zanhk** [comment] 2024-01-16 17:08
@kyoshino If you need help on this feature ping me!

**Comment by zanhk** [comment] 2024-03-31 10:46
Hi, is there any update on the Rich Text Editor progress?

**Comment by kyoshino** [comment] 2024-04-01 17:41
Another big task (#22) has just been completed, and I’ll be moving this forward shortly.

**Comment by zanhk** [comment] 2024-04-01 18:32
Nice. Looking forward to this, you should also check out what they used on keystatic because the ability to add custom components in MDX and MDOC is neat

**Comment by kyoshino** [comment] 2024-04-20 01:32
The long wait is over! Just shipped [v0.20.0](https://github.com/sveltia/sveltia-cms/releases/tag/v0.20.0) to provide a rich text editor! 🚀

**Closed by kyoshino** 2024-04-20 01:32 UTC
Labels: enhancement, P2

**Comment by fkrauthan** [comment] 2024-10-02 05:44
Any plans/idea when additional editor components (and potentially custom components) are becoming available? I would love to have Table support as well as adding a couple of custom components for layouting (e.g. columns) and embedded youtube videos.
